### ISSUE TITLE
Hydration scripts not showing up

### ISSUE THREAD

**Issue by confiscatedharddrive** [my-otter-self/MAS_hydro#1]
Hey, I just installed this mod and it shows up proper in the Submods section in the options menu when I launch the game but I can't find any menu for setting it up, even when looking up the term. I only see the conversation Monika had with me to tell me to hydrate. Your other mods work really well, I just think there's a snag with this one.

**Comment by my-otter-self** [comment]
hello! so i can help you, i need to know: is your random chatter on? in what setting?

**Comment by confiscatedharddrive** [comment]
Yup! It's on and on Normal setting.

**Comment by confiscatedharddrive** [comment]
Closing this issue due to it being resolved over Discord! New players might need to deselect "Repeat Topics" for it to show up.
